### ISSUE TITLE
Undeclared dependencies for tests: 'gt', 'huxtable'

### ISSUE THREAD

**Issue by barracuda156** [insightsengineering/formatters#102]
```
* checking package dependencies ... ERROR
Packages suggested but not available: 'gt', 'huxtable'

The suggested packages are required for a complete check.
Checking can be attempted without them by setting the environment
variable _R_CHECK_FORCE_SUGGESTS_ to a false value.

See section ‘The DESCRIPTION file’ in the ‘Writing R Extensions’
manual.
* DONE

Status: 1 ERROR
```

But these are not declared: https://cran.r-project.org/web/packages/formatters/index.html

**Comment by gmbecker** [comment]
Hi @barracuda156,

We do declare those, as you can see in https://github.com/insightsengineering/formatters/blob/main/DESCRIPTION

The (relatively old at this point, soon to be updated) version on CRAN did *not* have soft dependencies on those packages, thus the lack of them in the Suggests field there.

You can also see that the CRAN version is currently passing its checks, which includes a full R CMD check run, so that is safe to use (but will not have the features that involve huxtable or gt)
