### ISSUE TITLE
Add `disp` param to `var_labels()` or `labels` to `var_labels()`.

### ISSUE THREAD

**Issue by wwojciech** [insightsengineering/formatters#104]
Consider the following listing:
```
dat <- ex_adae
lsting <- as_listing(dat[1:25, ], disp_cols = c("USUBJID", "AESOC", "RACE", "AETOXGR", "BMRKR1"))
```
Now, in order to get the displayed columns with their labels I need to execute 
```
var_labels(lsting)[listing_dispcols(lsting)]
```
It would be nice to have:
```
var_labels(lsting, disp = TRUE)
```
or 
```
listing_dispcols(lsting, labels = TRUE)
```
I would propose to extend these 2 functions.

**Comment by gmbecker** [comment]
`var_labels` is a `formatters` function, which means it is not and cannot be specific to functionality in `rlistings`, so extending `var_labels` in a listing specific way (which the concept of 'display columns' is) isn't something we should be doing.

That said, the motivating issue sounds like a bug in `rlistings`, it should be respecting `var_labels` automatically, and if it isn't we should fix that there.

That said, I don't see the behavior you're describing:

```
> lsting <- as_listing(dat[1:25, ], disp_cols = c("USUBJID", "AESOC", "RACE", "AETOXGR", "BMRKR1"))
> lsting
Study Identifier   Unique Subject Identifier   Primary System Organ Class             Race              Analysis Toxicity Grade   Continous Level Biomarker 1
—————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
AB12345              AB12345-BRA-1-id-134                 cl B                        WHITE                        3                   6.46299057842479      
                     AB12345-BRA-1-id-134                 cl D                        WHITE                        3                   6.46299057842479      
                     AB12345-BRA-1-id-134                 cl A                        WHITE                        2                   6.46299057842479      
                     AB12345-BRA-1-id-134                 cl A                        WHITE                        2                   6.46299057842479      
```

Those are the labels in there, and they're the correct ones. The thing to remember here is that an `rlistings` listing object carries around *all the columns*, it just only displays the display columns, so that may be where the confusion is arising from.

**Comment by wwojciech** [comment]
@gmbecker, yes, I am sorry, I wanted to open this for `rlistings`, i.e. `listing_dispcols(lsting, labels = TRUE)`. I have not noticed `var_labels()` is in formatters. So, yes, not need to extend `var_labels()`

**Comment by gmbecker** [comment]
> @gmbecker, yes, I am sorry, I wanted to open this for `rlistings`, i.e. `listing_dispcols(lsting, labels = TRUE)`. I have not noticed `var_labels()` is in formatters. So, yes, not need to extend `var_labels()`

I think adding `listing_dispcol_labels` or `listing_displabels` would be better than adding an argument to `listing_dispcols`, as generally low-level functions should only do one thing. You can open an issue on rlistings with a bit more about why you need such a function and we can discuss it there @wwojciech
