### ISSUE TITLE
Is there a way to count the minimum number of line per page?

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/formatters#120]
This is the final table structure I am looking at:
```
>   table_structure(a[[1]])
[TableTree] root
 [TableTree] AEBODSYS
  [TableTree] cl A.1 [cont: 4 x 1]
   [TableTree] AEDECOD
    [TableTree] dcd A.1.1.1.2 [cont: 1 x 1]
     [ElementaryTable] AETOXGR (2 x 1)
>   table_structure(a[[2]])
[TableTree] root
 [TableTree] AEBODSYS
  [TableTree] cl B.2 [cont: 5 x 1]
   [TableTree] AEDECOD
    [TableTree] dcd B.2.2.3.1 [cont: 1 x 1]
     [ElementaryTable] AETOXGR (2 x 1)
```

I tried to find the correct minimum number for `lpp` (10 here in `a[[2]]` with 2 header rows) by using `make_row_df`, but I have troubles for tables like the one above that has multiple `summary_row_groups` an, hence, multiple content rows.

**Comment by gmbecker** [comment]
@Melkiades do you mean a minimum lpp that will successfully paginate without error, or do you mean the minimum amount of "repeat" (quotes cause it could e the first time) lines?

For the latter, if you have an rtables object (in which case this issue is somewhat ill-placed) you can look at 

```
rdf <- make_row_df(tbl)
max(rdf$par_extent + rdf$self_extent )  + nlines(col_info(tbl))
```

Which should give you the maximum number of lines that rendering a single row on a page plus all context and column header info etc.

This is NOT guaranteed to lead to a valid pagination though, its a lower bound. The only way to know the smallest number that will give you a successful pagination across the whole table that I can think of right now is doing a binary search through the possible lpp values and seeing which one succeeds in practice.

**Comment by Melkiades** [comment]
> @Melkiades do you mean a minimum lpp that will successfully paginate without error, or do you mean the minimum amount of "repeat" (quotes cause it could e the first time) lines?
> 
> For the latter, if you have an rtables object (in which case this issue is somewhat ill-placed) you can look at
> 
> ```
> rdf <- make_row_df(tbl)
> max(rdf$par_extent + rdf$self_extent )  + nlines(col_info(tbl))
> ```
> 
> Which should give you the maximum number of lines that rendering a single row on a page plus all context and column header info etc.
> 
> This is NOT guaranteed to lead to a valid pagination though, its a lower bound. The only way to know the smallest number that will give you a successful pagination across the whole table that I can think of right now is doing a binary search through the possible lpp values and seeing which one succeeds in practice.

Thanks, yep I was looking for finding a way to calculate and output valid "ranges" for lpp and cpp and widths and so on, i.e. so to limit the try-and-error process. Does it make sense making a function that does bin search?
