### ISSUE TITLE
`mform_handle_newlines` drops labels from `string` element

### ISSUE THREAD

**Issue by edelarua** [insightsengineering/formatters#122]
The `mform_handle_newlines` function drops colnames from the `strings` element when there is a newline character in a variable label. This causes issues downstream in the `rlistings::paginate_listings` function (see [related issue](https://github.com/insightsengineering/rlistings/issues/106)).

For example:

```r
dat <- ex_adae
dat <- dat |> var_relabel(AESOC = "System \n Organ Class")
lsting <- rlistings::as_listing(dat[1:25, ], disp_cols = c("USUBJID", "AESOC", "RACE", "AETOXGR", "BMRKR1"))

rlistings::paginate_listing(lsting, lpp = 20)
```
Returns error:
```
Error in rlistings::paginate_listing(lsting, lpp = 20) : 
  Assertion on 'names(colwidths)' failed: Must be setequal to {'STUDYID','USUBJID','AESOC','RACE','AETOXGR','BMRKR1'}, but has different type.
```

**Comment by gmbecker** [comment]
Ok, so the issue here is that that assertion is incorrect (or at the very least, not analogous to anything in `rtables`). 

`colwidths` are not required to be named. So while these names are being dropped, that is not an issue for any of the following machinery as far as i know.

column widths aren't matched by name, so requiring the names be there isn't actually providing any protection.

**Comment by edelarua** [comment]
In that case, we can close this issue/PR and fix this within a separate issue (if not already fixed by https://github.com/insightsengineering/rlistings/pull/109).

**Comment by gmbecker** [comment]
For completeness @edelarua, it turned out that in rlistings (before it got to the `formatters` machinery I was talking about) it was matching by name, but that doesn't match and in fact prevents generalization to `rtables` because "column names" in `rtables` is not really well defined in the general case. Columns are uniquely specified via (suitably specific) paths, but not by individual names. 

So I took the logic and the assertion out.

This does mean that `colwidths` has to match `listing_dispcols` _**by position**_, the same as they always have in the `rtables` context.
