### ISSUE TITLE
Missing unit test report

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/formatters#143]
when doing `R CMD check --as-cran`:

```
* checking CRAN incoming feasibility ... NOTE
Maintainer: ‘Gabriel Becker <gabembecker@gmail.com>’

Version contains large components (0.4.1.9001)

Found the following (possibly) invalid URLs:
  URL: https://insightsengineering.github.io/formatters/main/unit-test-report/
    From: README.md
    Status: 404
    Message: Not Found
```

**Comment by gmbecker** [comment]
@cicdguy ping on this. We will need it fixed before CRAN release

**Comment by shajoezhu** [comment]
pinging @walkowif on this.

**Comment by walkowif** [comment]
This is caused by the fact that [this step](https://github.com/insightsengineering/r.pkg.template/blob/main/.github/workflows/build-check-install.yaml#L288-L304) in the R CMD check workflow expects the file to be named `tests/testthat.R` in order to configure the JUnit reporter to save the result to `junit-result.xml`.
Instead of `tests/testthat.R`, there's `tests/run_tests.R` in the `formatters` repository.
This way, `junit-result.xml` is not generated and the unit test report is missing from the documentation.

There are two possibilities:
* renaming `tests/run_tests.R` to `tests/testthat.R`,
* or modifying the pkgdown configuration not to include the link to unit test report ([these two lines](https://github.com/insightsengineering/formatters/blob/main/_pkgdown.yml#L14C31-L15) will have to be removed)
