### ISSUE TITLE
Can you add "xx. (xx.x)" or "xx (xx.x)" 2d format labels?

### ISSUE THREAD

**Issue by freestatman** [insightsengineering/formatters#23]
Thanks for the nice tool!

Our use case is "n (pct)". "xx (xx.x%)" is not working for us because we dont keep the % sign in the parentheses. It will be great to enable more 2d format labels, such as "xx. (xx.x)" and "xx (xx.x)"?

Thanks,
Freeman

**Comment by freestatman** [comment]
Made an attempt to address this issue myself (https://github.com/freestatman/formatters), and it tries to add the following new format labels. I'm not sure if the "*100" label is intuitive enough for pct value without % sign (there may be beter one). If you like this attempt, I can make a PR. 

Thanks,
Freeman

  "xx (xx*100)", "xx (xx.*100)", "xx (xx.x*100)", "xx (xx.xx*100)",
  "xx. (xx.*100)", "xx.x (xx.x*100)", "xx.xx (xx.xx*100)",

  "xx (xx)", "xx (xx.)", "xx (xx.x)", "xx (xx.xx)",
  "xx. (xx)", "xx. (xx.)", "xx. (xx.x)", "xx. (xx.xx)",

**Comment by gmbecker** [comment]
Hi Freeman,

Thanks reaching out and filing an issue on this.

In terms of the `"xx (xx)"` style formats, we do have some in place ("xx.x (xx.x)" and "xx.xx (xx.xx)") and those do work, though obviously that is not the full compliment of combinations. I'm wary of combinatorial explosion here, to be honest, though it looks like we don't have as full a compliment as the ones with the percentage signs. This is likely because no one needed them when this was internal code, and I don't see a problem with fleshing out that set more completely. One thing to note here, very importantly, is that this is not a percent specific format so it does not multiply the second number by 100, and that (lack of) behavior isn't going to change becuase this is also a format often used for point estimate, se (or sd) pairs.

This will, unfortunately, mean that you will need to write either a custom summarization function or use a custom formatting function to get that multiplication to happen; both of those approaches will work.

The `"xx (xx*100)"` family of proposed formats I'm less sold on, currently;  there's a couple of issues related to this approach that are somewhat related to each-other, but they mostly boil down to the fact that I think generally formats should not be doing things to the values that they are applied to that could be done when generating the value.  I know that the percent related formats do the multiplication by 100 internally and thats what you're basing this on, but I'm not fully convinced that that would be the behavior if we were writing formatters from scratch today ( 
@waddella  may have a different view). Note that formats which encode conditionality are slightly different than this because that  cannot always be done beforehand without losing the raw value (in favor of, e.g., a string such as "> 999.99"). 

Related to this, format labels are not a formula language. I'm sure you know this, and you're not suggesting that we make it one, but `"xx (xx*100)"` makes it seem like they are one, and that, e.g., `"xx (xx*50)"` should also work (which it wont' and we're not going to change things so it does). In my experience the fact that users shouldn't want to do this is unlikely to prevent them from eventually trying to do it.

Let me talk it over with Adrian and see what we think

**Comment by freestatman** [comment]
Hi Gabe,
Thanks for sharing your insights. Naming things are difficult and I agree {formatters} is not supposed or designed to support combinatorial explosion. Just got another idea/proposal, maybe **"xx (pct.x)"** label is a better name for "n (pct)"? 

The following is exactly the approach we are taking to get the "n (pct)" without % sign, with the help of `sprintf_format()`. We can keep using such workaround, but enabling more format labels (e.g. "xx. (xx.x)" or "xx (pct.x)") can make our code a bit cleaner and more readable. :) 
> This will, unfortunately, mean that you will need to write either a custom summarization function or use a custom formatting function to get that multiplication to happen; both of those approaches will work.

Thanks,
Freeman

**Comment by gmbecker** [comment]
@freestatman I have added a number of 2d labels of the `"__ (__)"` form (again, none of which will do the `*100` part for you, that needs to happen in the value generation step, ie analysis/summary function).

I think this is the extent we'll be addressing this for now, I hope that is sufficient for your needs. Closing this issue for now. Please try v `>=0.2.0.3` from here, to see if it does. If not, please do reopen the issue.
