### ISSUE TITLE
Add example(s) to `make_row_df`

### ISSUE THREAD

**Issue by pawelru** [insightsengineering/formatters#95]
Please add example(s) to the `make_row_df` function. This is the function that is being referenced in other places as well so it's important to have a high quality docs in there

**Comment by gmbecker** [comment]
@pawelru this is an odd situation because `formatters` just defines the generic (and thus the signature) as well as what is expected to come out of it, there are no actual methods in formatters, so it isn't really possible/doesn't make sense to have an example here. 

Put in the parlance of a different OOP system, all we do in formatters re `make_row_df` is declare an interface, with no implementation. `rtables` and `rlistings` both separately implement that interface in order to use the pagination machinery implemented in formatters for it, which is also the reason the generic is not just defined in rtables.

We do discuss this function and using it for introspection of rtables objects in the introduction to rtables vignette: [https://roche.github.io/rtables/main/articles/introduction.html (section Introspecting](https://roche.github.io/rtables/main/articles/introduction.html#introspecting-rtables-table-objects)

**Comment by pawelru** [comment]
I understand. I am closing this then in favour of https://github.com/Roche/rtables/issues/518 to showoff methods and not generics. I was confused that rtables docs references this function from formatters and was looking for it in here.
